In [16]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

In [44]:
train = pd.read_csv('train.csv')
train.isna().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  160
smoking_status         0
stroke                 0
dtype: int64

In [45]:
train['bmi']=train['bmi'].fillna(train['bmi'].mean())

In [46]:
train=train.drop("id",axis=1)
s=pd.get_dummies(train['gender'])
smoking=pd.get_dummies(train['smoking_status']) 
train=pd.concat([train,s,smoking],axis=1) 
train=train.drop(['gender','smoking_status','ever_married','work_type','Residence_type','Other'], axis=1 )
x= train.drop('stroke',axis=1)
y=train['stroke']

In [47]:
train

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke,Female,Male,Unknown,formerly smoked,never smoked,smokes
0,36.0,0,0,67.29,36.7,0,1,0,0,1,0,0
1,34.0,0,0,83.53,48.5,0,1,0,0,1,0,0
2,60.0,0,0,65.16,30.8,0,0,1,0,0,1,0
3,75.0,0,0,78.80,29.3,1,1,0,0,1,0,0
4,76.0,0,0,58.65,25.6,0,0,1,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...
4083,53.0,1,0,98.61,38.8,0,1,0,0,0,0,1
4084,61.0,0,0,72.01,26.0,0,1,0,0,1,0,0
4085,44.0,0,0,94.71,28.4,0,0,1,0,0,0,1
4086,21.0,0,0,120.94,29.7,0,0,1,0,1,0,0
4087,58.0,1,0,59.52,33.2,0,1,0,0,0,1,0

In [48]:
from imblearn.over_sampling import SMOTE
from sklearn.model_selection import train_test_split
smote =  SMOTE(random_state=42)
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)
x_train, y_train = smote.fit_resample(x_train, y_train)
x_test, y_test = smote.fit_resample(x_test, y_test)

In [49]:
t=KNeighborsClassifier(n_neighbors=5, weights='distance',algorithm='kd_tree')
t.fit(x_train,y_train)
y_pre=t.predict(x_test)

In [54]:
test=pd.read_csv('test.csv')
id=test['id']
test=test.drop("id",axis=1)
test['bmi']=test['bmi'].fillna(train['bmi'].mean())
s=pd.get_dummies(test['gender'])
smoking=pd.get_dummies(test['smoking_status'])
test=pd.concat([test,s,smoking],axis=1)
test=test.drop(['gender','ever_married','work_type','Residence_type','smoking_status'], axis=1 )

In [55]:
y_pre2 =t.predict(test)

In [56]:
datatest=pd.DataFrame({'id': id,'stroke':y_pre2})
datatest.to_csv('pre.csv',index=False)
p=pd.read_csv('pre.csv')

In [57]:
p

         id  stroke
0     61960       0
1     31741       0
2     59451       0
3     40670       0
4     25391       0
...     ...     ...
1017   2953       1
1018  47799       0
1019  61013       0
1020  66400       0
1021   9013       0

[1022 rows x 2 columns]